arch:
  - amd64
  - ppc64le
language: java
jdk:
  - openjdk11
before_install:
  - |
    if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then 
     mkdir -p /opt/maven
     curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven
     export MAVEN_HOME=/opt/maven
     export PATH=${MAVEN_HOME}/bin:${PATH}
    fi
install:
  - mvn process-classes compile -Pnochecks -DskipTests > cxf.log
  - tail -300 cxf.log
  #tests
#  - mvn -f pom.xml install -Djava.awt.headless=true -fae -B
